print("=======================")
print("Tugas 1 SISOP kelas B")
print("=======================")
print("nama: Luqna Aziziyah")
print("NPM : 21083010020")
print("=======================")
print("notes: ")
print("=======================")
print("Hallo Dunia!")
print("Ini adalah skrip Bash pertamaku di linux")
print("=======================")
